### ISSUE TITLE
[parser] create parser for .ips files

### ISSUE THREAD

**Issue by kwouffe** [EC-DIGIT-CSIRC/sysdiagnose#14]
I identified 2 types of IPS files located in ./crashes_and_spins/ :

 * panic-full-XXX,ips
  * stacks-*.ips

Should be easy as the IPS format is... a json.
So maybe a parser to put together all the IPS files so it is easier to analyse/ingest in a consistent way

**Comment by cvandeplas** [comment]
To be implemented in `crashlogs.py`.

**Comment by cvandeplas** [comment]
implemented as part of #70
