### ISSUE TITLE
remove hard coded path `/home/david/.local/...`

### ISSUE THREAD

**Issue by aaronkaplan** [EC-DIGIT-CSIRC/sysdiagnose#17]
https://github.com/EC-DIGIT-CSIRC/sysdiagnose/blob/7951e574df6918e462f2b70096b09d9dc9957f32/parsers/sysdiagnose-logarchive.py#L42

**Comment by cvandeplas** [comment]
fixed in commit be65b6e4a084c659978950dc9c138dba17b5f7cc
