### ISSUE TITLE
(nice to have) UnifiedLogReader.py on Linux - parsing this is broken in Linux. Fix eventually

### ISSUE THREAD

**Issue by aaronkaplan** [EC-DIGIT-CSIRC/sysdiagnose#19]
https://github.com/EC-DIGIT-CSIRC/sysdiagnose/blob/f3fb49f60b8516fc31620f49d420c34a52331a9e/parsers/sysdiagnose-logarchive.py#L42

**Comment by cvandeplas** [comment]
this is because `sysdiagnose-logarchive.py` is using a system command.
```
cmd_parsing_osx = "/usr/bin/log show %s --style ndjson"  # fastest and short version
```
Note the existence [macos-UnifiedLogs from Mandiant](https://github.com/mandiant/macos-UnifiedLogs) that seems to be parsing those files in Rust

**Comment by cvandeplas** [comment]
See also https://www.mandiant.com/resources/blog/reviewing-macos-unified-logs

**Comment by cvandeplas** [comment]
Input was that the Mandiant tool seems to work quite well. A proposal is to integrate it in sysdiagnose:
- on mac systems use the native tool
- on linux use the Mandiant rust tool (needs to be built/compiled)

**Comment by aaronkaplan** [comment]
sounds good!

**Comment by cvandeplas** [comment]
Note: `unifiedlog_parser` is single threaded.  On my ryzon 7 pro system the iphoneOS `system_logs.logarchive` parsing took 45 seconds.
