### ISSUE TITLE
unify logarchive mac & linux model

### ISSUE THREAD

**Issue by aaronkaplan** [EC-DIGIT-CSIRC/sysdiagnose#2]
Need to implement the export and parsing via httsp://github.com/ydkhatri/UnifiedLogReader. The UnifiedLogReader has a different format than the OS X `/usr/bin/log show` command.

**Comment by cvandeplas** [comment]
I believe this is now done in commit be65b6e4a084c659978950dc9c138dba17b5f7cc

**Comment by cvandeplas** [comment]
I'll test it further once I have access to a mac

**Comment by aaronkaplan** [comment]
thanks

**Comment by cvandeplas** [comment]
> I believe this is now done in commit [be65b6e](https://github.com/EC-DIGIT-CSIRC/sysdiagnose/commit/be65b6e4a084c659978950dc9c138dba17b5f7cc)

correction: since that commit there is support for the unifiedlogreader, but the formats are still very different.
I'll have a look if it's possible to unify it in a way.

**Comment by cvandeplas** [comment]
unification at source is maybe not the best, as we'd need to re-process all the log files.
However, this can be caught by a library. In PR #64  I've added the `convert_entry_to_unifiedlog_format()` function in `parsers/logarchive.py`  to convert the apple format into unifiedlog_json.
Later we could consider a more transparent library (a LogarchiveReader perhaps?

**Comment by cvandeplas** [comment]
finally implemented it as the absence of an easy to use timestamp on the mandiant logarchive format was quite annoying.
Now the rest of the code should also be agnostic to the format.
