### ISSUE TITLE
sysdiagnose-timeliner.py: add more sources to export to timesketch and fix existing ones

### ISSUE THREAD

**Issue by aaronkaplan** [EC-DIGIT-CSIRC/sysdiagnose#23]
- [x] add more log files
line 24: add more logs:
``timestamps_files = { ...```
- [x] powerlog (line 70)

Go over the file and look at all TODOs

**Comment by cvandeplas** [comment]
I believe this is already implemented.
Let's open dedicated issues whenever we see files that contain timeline data that we want to include here.
