### ISSUE TITLE
(UC) geoloc + timestamp on known wifis

### ISSUE THREAD

**Issue by aaronkaplan** [EC-DIGIT-CSIRC/sysdiagnose#37]
create analzyer for that.

Maybe a GPS file output + timestamp. Load it in google earth.
Use: https://github.com/EC-DIGIT-CSIRC/sysdiagnose/blob/main/analyzers/sysdiagnose-wifi-gelocation.py

**Comment by cvandeplas** [comment]
that seems to be done in the `wifi_geolocation_kml` analyser
