### ISSUE TITLE
[Bug] Fix decoding of bytes in the plist cleaning functions

### ISSUE THREAD

**Issue by kwouffe** [EC-DIGIT-CSIRC/sysdiagnose#38]
Today its handled with 

d[k]=binascii.hexlify(v).decode('utf-8')

But it should handle differently outputs from the plist module
 - Data
 - UiD
 
 depending on the data it output with b' or b"

Maybe reading the code of the plist module would figure out how they handle different classes.

**Comment by cvandeplas** [comment]
I think this is already covered now with the changes I made ensuring all plists are loaded through the `load_plist_file_as_json()` function that uses the [json_serializable()](https://github.com/EC-DIGIT-CSIRC/sysdiagnose/blob/main/utils/misc.py#L59) function for decoding.
 
@kwouffe  can you please check and confirm?
