### ISSUE TITLE
Improve process parsing from taskinfo.txt

### ISSUE THREAD

**Issue by ddurvaux** [EC-DIGIT-CSIRC/sysdiagnose#51]
Retrieve proces and their PID from taskinfo.txt.

**Comment by cvandeplas** [comment]
The file structure looks similar to the `remotectl_dumpstate`.  (tab based indentation)
TODO: check if the code can be reused, if so, move functionality to a utils lib.

**Comment by cvandeplas** [comment]
Almost finished. Testing last thing next Tuesday.
