### ISSUE TITLE
parsers to contain list of files to match

### ISSUE THREAD

**Issue by cvandeplas** [EC-DIGIT-CSIRC/sysdiagnose#65]
Now the `initialise.py` script contains the mapping between parsers and files.

This mapping should be stored in each parser, because:
- it keeps information for a parser in one place
- it does not require a `x.json` case file to exist.
- when new parsers/files are added to the parser, old cases will also use those new features
- test cases can use this to know which files to look at

Implementation could be in a variable (list of regexes) or a function returning the list of files.
My current preference is the function, considering that allows more flexibility than a list of regexes. Downside is more complexity.

What are your thoughts?

**Comment by aaronkaplan** [comment]
I think that makes a lot (*a lot*) of sense.

**Comment by cvandeplas** [comment]
David just confirmed he also thinks it's a good idea.

**Comment by aaronkaplan** [comment]
let's :)

**Comment by cvandeplas** [comment]
Implementation is ongoing with the creation of test cases in #64 .

**Comment by cvandeplas** [comment]
implemented in PR #64
