### ISSUE TITLE
parser ps - autodetect line format based on header

### ISSUE THREAD

**Issue by cvandeplas** [EC-DIGIT-CSIRC/sysdiagnose#71]
First write some more test cases to ensure we don't break things.
Then investigate if it's possible to rewrite it dynamically: extract header, and use header as key for the variables when parsing the line

**Comment by cvandeplas** [comment]
fixed in 7c380cd6773df4c2df0b89cc397ebe25cfcb8648

**Comment by cvandeplas** [comment]
note: I could not use pandas as there were some inconsistencies in the structure

**Comment by cfossace** [comment]
hey just FYI you should add pandas to the `requirements.txt` :)

**Comment by cvandeplas** [comment]
nice catch @cfossace , that's fixed now in f26ac0c461e4b9c7c52d9e12d68153ff7991b069
