### ISSUE TITLE
[parser] logarchive parser shows errors on mac

### ISSUE THREAD

**Issue by cvandeplas** [EC-DIGIT-CSIRC/sysdiagnose#93]
Ensure these are not an issue, and if so, ensure they don't get shown in the output.
```
(venv) chri@Christophes-iMac sysdiagnose % ./sysdiagnose.py -c public parse logarchive            
Case ID: public
Parser 'logarchive' for case ID 'public'
WARNING: error parsing JSON ==========
: Expecting value: line 1 column 1 (char 0)
WARNING: error parsing JSON /Users/chri/Desktop/cases/public/data/sysdiagnose_2023.05.24_13-29-15-0700_iPhone-OS_iPhone_19H349/system_logs.logarchive
: Expecting value: line 1 column 1 (char 0)
WARNING: error parsing JSON ==========
: Expecting value: line 1 column 1 (char 0)
```

**Comment by dario-br** [comment]
I think I know, what it can be... last message of log show command.

See some extract from method `__convert_using_native_logparser` more precisely from `LogarchiveParser.__execute_cmd_and_yield_result`:

```bash
{"timezoneName":"","messageType":"Default","eventType":"logEvent","source":null,REDACTED}

{"count":130555,"finished":1}

==========
FILE_NAME
==========
```

When running the native command: the output resembles, but without the filename. 

```bash
{"timezoneName":"","messageType":"Default","eventType":"logEvent","source":null,REDACTED}
{"count":130555,"finished":1}
```

**Comment by dario-br** [comment]
So, the culprit lines are the 
'''bash
==========
FILE_NAME
==========
'''
Because they cannot be transformed into json by `json.loads`.

We can potentially (if we are sure that they only `KeyError` exception is generated by the last line. Change the error handling of `__convert_using_native_logparser`:

'''python
                except KeyError:
                    # last line of log does not contain 'time' field, nor the rest of the data.
                    # so just ignore it
                    pass
'''

by 

'''python
                except KeyError:
                    # last line of log does not contain 'time' field, nor the rest of the data.
                    # so just ignore it
                    break
'''

Do you agree @cvandeplas ? If so, I create a PR
