### ISSUE TITLE
JoinedByUserAt and other timestamps removed

### ISSUE THREAD

**Issue by cfossace** [EC-DIGIT-CSIRC/sysdiagnose#94]
The WiFi Known Networks parser removes all timestamps from the file when it parses the plist. Timestamps such as:

JoinedByUserAt
AddedAt
JoinedBySystemAt

Are missing. Trying to single step through the parser has been tough... where is this defined?

**Comment by cfossace** [comment]
I attempted to fix this with PR https://github.com/EC-DIGIT-CSIRC/sysdiagnose/pull/95

**Comment by cvandeplas** [comment]
nice catch !  
I've just merged the PR
